### ISSUE TITLE
getting a install error "invalid syntax"

### ISSUE THREAD

**Issue by iukea1** [Elemental-attack/Elemental#2]
Hello attached is a picture of the error I am getting. Was curious if you could provide any words of wisdom 
![image](https://user-images.githubusercontent.com/35882815/71311609-cb173480-23e5-11ea-915a-fab21ed146ef.png)

**Comment by exec-bypass** [comment]
Hi, please use Python 3 to resolve this issue.

**Comment by iukea1** [comment]
Same issue in python 3.6

**Comment by exec-bypass** [comment]
Hi,
manage.py is automatically created for any new Django project and not something developed by Elemental. Not sure why you're still having the issue on 3. I was able to recreate your issue on Python 2, but not 3. I'd recommend trying on a different system.
